---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging, SnapLock charging, CIFS charging, audit volumes, primary volumes, volume-based charging 
summary: Familiarisez-vous avec la facturation, le modèle de consommation, la tarification et les configurations des licences basées sur la capacité. 
---
= En savoir plus sur les licences basées sur la capacité pour Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez vous familiariser avec la facturation et l'utilisation de la capacité pour les licences basées sur la capacité.



== Modèles de consommation ou options d'achat de licences

Des formules de licences basées sur la capacité sont disponibles avec les modèles de consommation ou options d'achat suivants :

* *BYOL* : Apportez votre propre permis de conduire (BYOL).  Une licence achetée auprès de NetApp qui peut être utilisée pour déployer Cloud Volumes ONTAP chez n’importe quel fournisseur de cloud.
+

NOTE: NetApp a restreint l'achat, la prolongation et le renouvellement des licences BYOL. Pour plus d'informations, consultez  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Disponibilité restreinte des licences BYOL pour Cloud Volumes ONTAP"^] .



ifdef::azure[]

endif::azure[]

* *PAYGO* : Un abonnement à la carte (PAYGO) est un abonnement horaire proposé par la place de marché de votre fournisseur de cloud.
* *Annuel* : Un contrat annuel de la place de marché de votre fournisseur de cloud.


Notez ce qui suit :

* Si vous achetez une licence auprès de NetApp (BYOL), vous devez également souscrire à l'offre PAYGO sur la marketplace de votre fournisseur cloud. NetApp a restreint les licences BYOL. À l'expiration de vos licences BYOL, vous devez les remplacer par des abonnements à la marketplace cloud.
+
Votre licence est toujours facturée en premier, mais vous serez facturé au tarif horaire du marché dans ces cas :

+
** Si vous dépassez votre capacité autorisée
** Si la durée de votre licence expire


* Si vous disposez d'un contrat annuel auprès d'une place de marché, _tous_ les systèmes Cloud Volumes ONTAP que vous déployez sont facturés sur ce contrat.  Vous ne pouvez pas combiner un contrat de marché annuel avec BYOL.
* Seuls les systèmes à nœud unique avec BYOL sont pris en charge dans les régions de Chine. Les déploiements dans les régions de Chine sont exemptés des restrictions de licence BYOL.




== Modification des packs de licences

Après le déploiement, vous pouvez modifier le package pour un système Cloud Volumes ONTAP qui utilise des licences basées sur la capacité.  Par exemple, si vous avez déployé un système Cloud Volumes ONTAP avec le package Essentials, vous pouvez le remplacer par le package Professional si les besoins de votre entreprise ont changé.

link:task-manage-capacity-licenses.html["Apprenez à changer de méthode de charge"] .

Pour plus d'informations sur la conversion des licences basées sur les nœuds en licences basées sur la capacité, consultez



== Comment sont facturés les types et forfaits de stockage pris en charge

La facturation dans Cloud Volumes ONTAP est basée sur un certain nombre de facteurs, tels que les forfaits et les types de volumes. Les packages de licences basés sur la capacité sont disponibles avec Cloud Volumes ONTAP 9.7 et versions ultérieures.

Pour plus de détails sur les prix, rendez-vous sur le https://bluexp.netapp.com/pricing/["Site Web de la NetApp Console"^] .



=== Machines virtuelles de stockage

* Il n'y a pas de frais de licence supplémentaires pour les machines virtuelles de stockage de données supplémentaires (SVM), mais il y a des frais de capacité minimum de 4 Tio par SVM de stockage de données.
* Les SVM de reprise après sinistre sont facturés en fonction de la capacité provisionnée.




=== paires HA

Pour les paires HA, vous n'êtes facturé que pour la capacité provisionnée sur un nœud.  Vous n'êtes pas facturé pour les données mises en miroir de manière synchrone sur le nœud partenaire.



=== Volumes FlexClone et FlexCache

* Vous ne serez pas facturé pour la capacité utilisée par les volumes FlexClone .
* Les volumes FlexCache source et de destination sont considérés comme des données principales et facturés en fonction de l'espace provisionné.




=== Volumes de lecture/écriture

Si vous créez ou utilisez un volume inscriptible (lecture/écriture), il est considéré comme un volume principal et est facturé pour la capacité provisionnée sur la base du coût minimum par machine virtuelle de stockage (SVM).  On peut citer comme exemples les volumes de lecture/écriture FlexVol , les volumes d'audit SnapLock et les volumes d'audit CIFS/NFS.  Tous les volumes de données créés par l'utilisateur sont facturés conformément à votre abonnement et à votre type de forfait.  Les volumes internes ONTAP créés automatiquement et ne pouvant pas stocker de données, tels que les volumes racine SVM, ne sont pas facturés.



=== forfaits essentiels

Avec le forfait Essentials, vous êtes facturé en fonction du type de déploiement (HA ou nœud unique) et du type de volume (principal ou secondaire).  La tarification du plus élevé au plus bas est présentée dans l'ordre suivant : _Essentials Primary HA_, _Essentials Primary Single Node_, _Essentials Secondary HA_ et _Essentials Secondary Single Node_.  Alternativement, lorsque vous achetez un contrat de marché ou acceptez une offre privée, les frais de capacité sont les mêmes pour tout type de déploiement ou de volume.

L'octroi de licences est entièrement basé sur le type de volume créé dans les systèmes Cloud Volumes ONTAP :

* Essentials Single Node : volumes en lecture/écriture créés sur un système Cloud Volumes ONTAP à l'aide d'un seul nœud ONTAP .
* Essentials HA : volumes de lecture/écriture à l'aide de deux nœuds ONTAP pouvant basculer l'un vers l'autre pour un accès aux données sans interruption.
* Essentials Secondary Single Node : volumes de type Data Protection (DP) (généralement des volumes de destination SnapMirror ou SnapVault en lecture seule) créés sur un système Cloud Volumes ONTAP à l'aide d'un seul nœud ONTAP .
+

NOTE: Si un volume en lecture seule/DP devient un volume principal, la console le considère comme des données principales et les coûts de facturation sont calculés en fonction du temps pendant lequel le volume était en mode lecture/écriture.  Lorsque le volume est à nouveau rendu en lecture seule/DP, il considère à nouveau le volume comme des données secondaires et facture en conséquence en utilisant la licence la plus correspondante dans la console.

* Essentials Secondary HA : volumes de type Data Protection (DP) (généralement des volumes de destination SnapMirror ou SnapVault en lecture seule) créés sur un système Cloud Volumes ONTAP à l'aide de deux nœuds ONTAP qui peuvent basculer l'un vers l'autre pour un accès aux données sans interruption.




== Limite de capacité

Dans le modèle de licence basé sur la capacité, chaque système Cloud Volumes ONTAP prend en charge la hiérarchisation du stockage d'objets, et la capacité hiérarchisée totale peut évoluer jusqu'à la limite de compartiment du fournisseur de cloud. Bien que la licence n'impose pas de restrictions de capacité, suivez les https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Bonnes pratiques de FabricPool"^] pour garantir des performances, une fiabilité et une rentabilité optimales lors de la configuration et de la gestion de la hiérarchisation.

Pour plus d'informations sur les limites de capacité de chaque fournisseur de cloud, reportez-vous à leur documentation :

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["Documentation AWS"^]
* https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["Documentation Azure pour les disques gérés"^]et https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Documentation Azure pour le stockage d'objets blob"^]
* https://cloud.google.com/storage/docs/buckets["Documentation Google Cloud"^]




== Nombre maximal de systèmes

Avec une licence basée sur la capacité, le nombre maximal de systèmes Cloud Volumes ONTAP est limité à 24 par organisation NetApp Console. Un  est une paire haute disponibilité Cloud Volumes ONTAP, un système Cloud Volumes ONTAP à nœud unique, ou toute machine virtuelle de stockage supplémentaire que vous créez. La machine virtuelle de stockage par défaut n'est pas prise en compte dans la limite. Cette limite s'applique à tous les modèles de licence.

Par exemple, disons que vous avez trois systèmes :

* Un système Cloud Volumes ONTAP à nœud unique avec une machine virtuelle de stockage (il s'agit de la machine virtuelle de stockage par défaut créée lorsque vous déployez Cloud Volumes ONTAP)
+
Ce système compte comme un seul système.

* Un système Cloud Volumes ONTAP à nœud unique avec deux machines virtuelles de stockage (la machine virtuelle de stockage par défaut, plus une machine virtuelle de stockage supplémentaire que vous avez créée)
+
Ce système compte comme deux systèmes : un pour le système à nœud unique et un pour la machine virtuelle de stockage supplémentaire.

* Une paire Cloud Volumes ONTAP HA avec trois machines virtuelles de stockage (la machine virtuelle de stockage par défaut, plus deux machines virtuelles de stockage supplémentaires que vous avez créées)
+
Ce système compte trois systèmes : un pour la paire HA et deux pour les machines virtuelles de stockage supplémentaires.



Cela représente six systèmes au total. Vous auriez alors de la place pour 14 systèmes supplémentaires dans votre organisation.

Si vous avez un déploiement important nécessitant plus de 24 systèmes, contactez votre représentant commercial ou votre équipe de vente.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["En savoir plus sur les limites de stockage pour AWS, Azure et Google Cloud"^] .



== Frais minimum

Des frais minimum de 4 Tio sont appliqués pour chaque machine virtuelle de stockage de données possédant au moins un volume principal (lecture-écriture).  Si la somme des volumes principaux est inférieure à 4 Tio, la console applique les frais minimum de 4 Tio à cette machine virtuelle de stockage.

Si vous n'avez pas encore provisionné de volumes, les frais minimum ne s'appliquent pas.

Pour le package Essentials, les frais de capacité minimale de 4 Tio ne s'appliquent pas aux machines virtuelles de stockage qui contiennent uniquement des volumes secondaires (protection des données). Par exemple, si vous disposez d'une machine virtuelle de stockage avec 1 Tio de données secondaires, vous êtes facturé uniquement pour ces 1 Tio de données. Avec le type de forfait Professionnel, la facturation de capacité minimale de 4 Tio s'applique quel que soit le type de volume.



== Préférences de facturation et dépassements

Vous pouvez choisir votre mode de facturation dans la section * Licenses and subscriptions* de la Console. Des dépassements surviennent lorsque votre utilisation excède la capacité spécifiée dans votre licence ou votre abonnement annuel.

* * Licences NetApp en premier * : Dans ce modèle, votre utilisation est d'abord facturée en fonction de la capacité de votre forfait de licences (BYOL). Si vous dépassez la capacité de votre licence, les dépassements sont facturés en fonction de votre abonnement annuel à la place de marché ou des tarifs horaires à la demande de la place de marché (PAYGO). Si votre licence BYOL expire, vous devez passer à un modèle de licence basé sur la capacité via les places de marché cloud. Pour plus d'informations, veuillez consulter link:task-convert-node-capacity.html["Convertir une licence basée sur un nœud Cloud Volumes ONTAP en une licence basée sur la capacité"].
* *Abonnements Marketplace uniquement* : Dans ce modèle, votre consommation est d’abord imputée à votre abonnement annuel Marketplace. Toute utilisation supplémentaire est facturée aux tarifs horaires à la demande du marché (PAYGO). Toute capacité de licence inutilisée est ignorée pour la facturation.


Pour plus d'informations sur les préférences de facturation, veuillez consulter https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Découvrez les préférences de facturation pour les licences et les abonnements."^].



=== Comment les dépassements sont facturés pour les licences Essentials

Si vous achetez une licence Essentials auprès de NetApp (BYOL) et que vous dépassez la capacité sous licence pour un package Essentials spécifique, la console facture les dépassements sur une licence Essentials plus chère (si vous en avez une avec une capacité disponible).  La console utilise d'abord la capacité disponible pour laquelle vous avez payé avant de facturer le marché.  S'il n'y a pas de capacité disponible avec votre licence BYOL, la capacité excédentaire est facturée aux tarifs horaires à la demande du marché (PAYGO) et ajoutée à votre facture mensuelle.

De même, si vous disposez d'un contrat annuel sur le marché ou d'une offre privée comprenant plusieurs forfaits Essentials, et que votre utilisation dépasse la capacité prévue pour un type de déploiement et de volume d'un forfait spécifique, la console facture les dépassements sur un forfait Essentials plus cher en fonction de sa capacité disponible.  Une fois cette capacité épuisée, le surplus restant est facturé aux tarifs horaires à la demande du marché (PAYGO) et ajouté à votre facture mensuelle.

Pour plus d'informations sur la facturation des licences Essentials, veuillez consulterlink:concept-licensing-charging.html#essentialscharging["forfaits essentiels"] .

Voici un exemple. Disons que vous disposez des licences suivantes pour le package Essentials :

* Une licence _Essentials Secondary HA_ de 500 Tio avec 500 Tio de capacité engagée
* Une licence _Essentials Single Node_ de 500 Tio qui ne dispose que de 100 Tio de capacité engagée


50 Tio supplémentaires sont provisionnés sur une paire HA avec des volumes secondaires.  Au lieu de facturer ces 50 Tio au PAYGO, la console facture le dépassement de 50 Tio sur la licence _Essentials Single Node_.  Cette licence est plus chère que _Essentials Secondary HA_, mais elle utilise une licence que vous avez déjà achetée et n'ajoutera pas de frais à votre facture mensuelle.

Dans *Administration > Licenses and subscriptions*, vous pouvez voir 50 Tio facturés sur la licence _Essentials Single Node_.

Voici un autre exemple.  Disons que vous disposez des licences suivantes pour le package Essentials :

* Une licence _Essentials Secondary HA_ de 500 Tio avec 500 Tio de capacité engagée
* Une licence _Essentials Single Node_ de 500 Tio qui ne dispose que de 100 Tio de capacité engagée


100 Tio supplémentaires sont provisionnés sur une paire HA avec des volumes primaires.  La licence que vous avez achetée ne dispose pas de capacité engagée _Essentials Primary HA_.  La licence _Essentials Primary HA_ est proposée à un prix plus élevé que les licences _Essentials Primary Single Node_ et _Essentials Secondary HA_.

Dans cet exemple, la console facture les dépassements au tarif du marché pour les 100 Tio supplémentaires.  Les frais de dépassement apparaîtront sur votre facture mensuelle.
