---
sidebar: sidebar 
permalink: concept-degraded-ha-pair.html 
keywords: storage takeover, storage giveback, degraded, degraded status, degraded state, ha pair, ha takeover, takeover, giveback 
summary: 'Lorsqu"un nœud d"une paire HA n"est pas disponible, l"autre nœud fournit des données à son partenaire pour fournir un service de données continu.  C"est ce qu"on appelle la prise de contrôle du stockage.  Plusieurs actions ne sont pas disponibles tant que la restitution en stockage n"est pas terminée.' 
---
= Opérations indisponibles lorsqu'un nœud de la paire Cloud Volumes ONTAP HA est hors ligne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsqu'un nœud d'une paire HA n'est pas disponible, l'autre nœud fournit des données à son partenaire pour fournir un service de données continu.  C'est ce qu'on appelle la _prise de contrôle du stockage_.  Plusieurs actions ne sont pas disponibles tant que la restitution en stockage n'est pas terminée.


TIP: Lorsqu'un nœud d'une paire HA n'est pas disponible, l'état du système dans la console NetApp est _Dégradé_.

Les actions suivantes ne sont pas disponibles à partir de la prise de contrôle du stockage :

* Enregistrement du support
* Modifications de licence
* Modifications du type d'instance ou de machine virtuelle
* Modifications de la vitesse d'écriture
* Configuration CIFS
* Modification de l'emplacement des sauvegardes de configuration
* Définition du mot de passe du cluster
* Gestion des disques et des agrégats (allocation avancée)


Ces actions sont à nouveau disponibles une fois la restitution du stockage terminée et l'état du système redevient normal.
