---
sidebar: sidebar 
permalink: concept-write-speed.html 
keywords: write speed, high write speed, normal write speed, nvfail, writing speed, ldm, low durability mode 
summary: 'La NetApp Console vous permet de choisir une vitesse d"écriture normale ou élevée pour Cloud Volumes ONTAP.  Avant de choisir une vitesse d’écriture, vous devez comprendre les différences entre les paramètres normaux et élevés, ainsi que les risques et les recommandations lors de l’utilisation d’une vitesse d’écriture élevée.' 
---
= Découvrez la vitesse d'écriture sur Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console vous permet de choisir une vitesse d'écriture normale ou élevée pour la plupart des configurations Cloud Volumes ONTAP .  Avant de choisir une vitesse d’écriture, vous devez comprendre les différences entre les paramètres normaux et élevés, ainsi que les risques et les recommandations lors de l’utilisation d’une vitesse d’écriture élevée.



[[normal-write-speed]]
== Vitesse d'écriture normale

Lorsque vous choisissez une vitesse d’écriture normale, les données sont écrites directement sur le disque.  Lorsque les données sont écrites directement sur le disque, cela réduit le risque de perte de données en cas de panne système imprévue ou de panne en cascade impliquant une panne système imprévue (paires HA uniquement).

La vitesse d’écriture normale est l’option par défaut.



[[high-write-speed]]
== Vitesse d'écriture élevée

Lorsque vous choisissez une vitesse d'écriture élevée, les données sont mises en mémoire tampon avant d'être écrites sur le disque, ce qui offre des performances d'écriture plus rapides.  En raison de cette mise en cache, il existe un risque de perte de données en cas de panne imprévue du système.

La quantité de données pouvant être perdue en cas de panne imprévue du système correspond à la durée des deux derniers points de cohérence.  Un point de cohérence est l’acte d’écrire des données mises en mémoire tampon sur le disque.  Un point de cohérence se produit lorsque le journal d'écriture est plein ou après 10 secondes (selon la première éventualité).  Cependant, les performances du stockage fourni par votre fournisseur de cloud peuvent affecter le temps de traitement du point de cohérence.



[[when-to-use-high-write-speed]]
=== Quand utiliser une vitesse d'écriture élevée

Une vitesse d'écriture élevée est un bon choix si des performances d'écriture rapides sont requises pour votre charge de travail et que vous pouvez résister au risque de perte de données en cas de panne système imprévue ou de panne en cascade impliquant une panne système imprévue (paires HA uniquement).



[[recommendations-when-using-high-write-speed]]
=== Recommandations lors de l'utilisation d'une vitesse d'écriture élevée

Si vous activez une vitesse d'écriture élevée, vous devez garantir la protection en écriture au niveau de la couche applicative ou vous assurer que les applications peuvent tolérer une perte de données, le cas échéant. Toutes les configurations de Cloud Volumes ONTAP ne prennent pas en charge la vitesse d'écriture élevée. Ces configurations utilisent par défaut la vitesse d'écriture normale.



[[high-write-speed-in-aws]]
=== Vitesse d'écriture élevée dans AWS

Systèmes à nœud unique:: Si vous utilisez un système à nœud unique, Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec tous les types d'instances.
paires HA:: À partir de la version 9.8, Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec des paires HA lors de l'utilisation de presque tous les types d'instances EC2 pris en charge, à l'exception de m5.xlarge et r5.xlarge.
+
--
link:reference-configs-aws.html["En savoir plus sur les instances Amazon EC2 prises en charge par Cloud Volumes ONTAP"]. Si vous prévoyez d'activer une vitesse d'écriture élevée sur une paire haute disponibilité dans AWS, vous devez comprendre la différence de niveaux de protection entre un déploiement sur plusieurs zones de disponibilité (AZ) et un déploiement sur une seule AZ. Le déploiement d'une paire haute disponibilité sur plusieurs AZ offre une meilleure résilience et contribue à réduire le risque de perte de données.

link:concept-ha.html["En savoir plus sur les paires HA dans AWS"] .

--




[[high-write-speed-in-azure]]
=== Vitesse d'écriture élevée dans Azure

Systèmes à nœud unique:: Si vous utilisez un système à nœud unique, Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec tous les types de VM.
paires HA:: Si vous utilisez une paire haute disponibilité, Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec plusieurs types de machines virtuelles, à partir de la version 9.8. Accédez à la link:reference-configs-azure.html["Notes de version de Cloud Volumes ONTAP"] pour consulter les types de machines virtuelles qui prennent en charge une vitesse d'écriture élevée.




[[high-write-speed-in-google-cloud]]
=== Vitesse d'écriture élevée dans Google Cloud

Systèmes à nœud unique:: Si vous utilisez un système à nœud unique, Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec tous les types de machines.
paires HA:: Si vous utilisez une paire haute disponibilité, Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec plusieurs types de machines virtuelles, à partir de la version 9.13.0. Accédez à la link:reference-configs-gcp.html#supported-configurations-by-license["Notes de version de Cloud Volumes ONTAP"^] pour consulter les types de machines virtuelles qui prennent en charge une vitesse d'écriture élevée.
+
--
link:reference-configs-gcp.html["En savoir plus sur les types de machines Google Cloud pris en charge par Cloud Volumes ONTAP"^].

--




[[how-to-select-a-write-speed]]
== Comment sélectionner une vitesse d'écriture

Vous pouvez choisir une vitesse d'écriture lorsque vous ajoutez un nouveau système Cloud Volumes ONTAP et vous pouvezlink:task-modify-write-speed.html["modifier la vitesse d'écriture d'un système existant"] .



[[what-to-expect-if-data-loss-occurs]]
== À quoi s'attendre en cas de perte de données

Si une perte de données se produit en raison d'une vitesse d'écriture élevée, le système de gestion des événements (EMS) signale les deux événements suivants :

* Cloud Volumes ONTAP 9.12.1 ou version ultérieure
+
 NOTICE nv.data.loss.possible: An unexpected shutdown occurred while in high write speed mode, which possibly caused a loss of data.
* Cloud Volumes ONTAP 9.11.0 à 9.11.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown with High Write Speed mode"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect..
* Cloud Volumes ONTAP 9.8 à 9.10.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect.


Lorsque cela se produit, Cloud Volumes ONTAP doit pouvoir démarrer et continuer à diffuser des données sans intervention de l’utilisateur.



[[how-to-stop-data-access-if-data-loss-occurs]]
=== Comment arrêter l'accès aux données en cas de perte de données

Si vous êtes préoccupé par la perte de données, que vous souhaitez que les applications cessent de s'exécuter en cas de perte de données et que l'accès aux données reprenne une fois le problème de perte de données correctement résolu, vous pouvez utiliser l'option NVFAIL de la CLI pour atteindre cet objectif.

Pour activer l'option NVFAIL:: `vol modify -volume <vol-name> -nvfail on`
Pour vérifier les paramètres NVFAIL:: `vol show -volume <vol-name> -fields nvfail`
Pour désactiver l'option NVFAIL:: `vol modify -volume <vol-name> -nvfail off`


En cas de perte de données, un volume NFS ou iSCSI avec NVFAIL activé doit cesser de diffuser des données (il n'y a aucun impact sur CIFS qui est un protocole sans état).  Pour plus de détails, reportez-vous à https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/GUID-40D04B8A-01F7-4E87-8161-E30BD80F5B7F.html["Comment NVFAIL affecte l'accès aux volumes NFS ou aux LUN"^] .

Pour vérifier l'état NVFAIL:: `vol show -fields in-nvfailed-state`


Une fois le problème de perte de données correctement résolu, vous pouvez effacer l’état NVFAIL et le volume sera disponible pour l’accès aux données.

Pour effacer l'état NVFAIL:: `vol modify -volume <vol-name> -in-nvfailed-state false`

