---
sidebar: sidebar 
permalink: concept-degraded-ha-pair.html 
keywords: 'high-availability (HA) configuration in Cloud Volumes ONTAP, CVO HA, storage takeover, storage giveback, degraded, degraded status, ha takeover, takeover, giveback, disaster recovery, svm disaster recovery, storage vm dr' 
summary: 'Une configuration à haute disponibilité (HA) dans Cloud Volumes ONTAP garantit la continuité des activités et la tolérance aux pannes pour votre solution de stockage haute performance.' 
---
= Configuration haute disponibilité de Cloud Volumes ONTAP
:allow-uri-read: 


[role="lead"]
Une configuration haute disponibilité (HA) dans Cloud Volumes ONTAP garantit la continuité d'activité et la tolérance aux pannes de votre solution de stockage haute performance. En déployant deux nœuds ONTAP sur des domaines de panne distincts, le système assure un fonctionnement sans interruption (NDO) et un basculement transparent en cas de panne matérielle, d'interruption réseau ou de maintenance de routine.

Déployez une paire haute disponibilité lorsque votre architecture l'exige :

* *Charges de travail critiques* : Bases de données et applications d’entreprise qui ne peuvent tolérer une interruption.
* *Mises à niveau non perturbatrices* : mises à niveau vers des versions ONTAP ou modifications des instances de calcul cloud sous-jacentes sans mettre le stockage hors ligne.
* *Résilience multizone* : Protection contre les défaillances isolées de zones de disponibilité au sein d’une région cloud.




[[how-ha-pairs-work]]
== Fonctionnement des paires haute disponibilité

Du point de vue de la gestion, la configuration HA fonctionne comme un cluster actif-actif, tandis que chaque agrégat de données appartient à un nœud spécifique.

* *Réplication synchrone* : Les données écrites dans la NVRAM du nœud principal sont répliquées de manière synchrone dans la NVRAM du nœud partenaire avant que l’écriture ne soit confirmée au client.
* *Prise en charge d'une instance de médiateur* : Une instance de médiateur tierce surveille l'état des deux nœuds. Si le nœud principal ne répond plus, le médiateur orchestre une prise de contrôle du stockage.
* *Prise de contrôle du stockage* : Le nœud survivant prend possession des agrégats de stockage et des interfaces réseau du partenaire, reprenant le service de données en quelques secondes.




[[ha-configuration-requirements-and-limitations]]
== Exigences et limitations de configuration HA

Lors du déploiement d'une paire haute disponibilité dans Cloud Volumes ONTAP, tenez compte des exigences et limitations suivantes :

* *Dimensionnement des ressources de calcul* : Les deux nœuds d’une paire haute disponibilité doivent utiliser exactement le même type d’instance de calcul cloud ou la même configuration de machine.
* *Prise en charge du protocole* : La disponibilité continue (CA) SMB/CIFS est prise en charge pour les charges de travail Hyper-V et SQL Server, mais nécessite des indicateurs de configuration ONTAP spécifiques.
* *Temps de basculement* : Bien que la prise de contrôle du stockage soit généralement mesurée en secondes, les paramètres de délai d’expiration côté client (comme les délais d’expiration de l’initiateur iSCSI) doivent être correctement configurés pour éviter toute interruption de l’application.




[[operations-unavailable-when-a-node-in-an-ha-pair-is-offline]]
== Opérations indisponibles lorsqu'un nœud d'une paire haute disponibilité est hors ligne

Lorsqu'un nœud d'une paire HA n'est pas disponible, l'autre nœud fournit des données à son partenaire pour fournir un service de données continu.  C'est ce qu'on appelle la _prise de contrôle du stockage_.  Plusieurs actions ne sont pas disponibles tant que la restitution en stockage n'est pas terminée.


TIP: Lorsqu'un nœud d'une paire HA n'est pas disponible, l'état du système dans la NetApp Console est _Dégradé_.

Les actions suivantes ne sont pas disponibles à partir de la prise de contrôle du stockage :

* Enregistrement du support
* Modifications de licence
* Modifications du type d'instance ou de machine virtuelle
* Modifications de la vitesse d'écriture
* Configuration CIFS
* Modification de l'emplacement des sauvegardes de configuration
* Définition du mot de passe du cluster
* Gestion des disques et des agrégats (allocation avancée)


Ces actions sont à nouveau disponibles une fois la restitution du stockage terminée et l'état du système redevient normal.



[[storage-vm-disaster-recovery-for-cloud-volumes-ontap]]
== Reprise après sinistre des machines virtuelles de stockage pour Cloud Volumes ONTAP

La NetApp Console ne propose pas de prise en charge de la configuration ou de l'orchestration pour la reprise après sinistre (DR) des machines virtuelles de stockage (SVM). Pour configurer la DR pour Cloud Volumes ONTAP, vous devez utiliser ONTAP System Manager ou l'interface de ligne de commande ONTAP pour configurer la réplication SVM SnapMirror.

Si vous configurez la réplication SVM SnapMirror entre deux systèmes Cloud Volumes ONTAP, la réplication doit s’effectuer entre deux systèmes en paire haute disponibilité ou deux systèmes à nœud unique. Vous ne pouvez pas configurer la réplication SVM SnapMirror entre une paire haute disponibilité et un système à nœud unique.

Reportez-vous aux documents suivants pour obtenir les instructions de l'interface de ligne de commande ONTAP .

* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guide de préparation express à la reprise après sinistre SVM"^]
* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guide de reprise après sinistre SVM Express"^]


.Liens connexes
* link:concept-ha.html["En savoir plus sur les paires Cloud Volumes ONTAP HA dans AWS"]
* link:concept-ha-azure.html["En savoir plus sur les paires Cloud Volumes ONTAP HA dans Azure"]
* link:concept-ha-google-cloud.html["Découvrez les paires haute disponibilité Cloud Volumes ONTAP dans GCP"]

