---
settings:
  name: Cloud Volumes ONTAP
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Fournisseur de cloud
    default: Tous les fournisseurs de cloud
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azuré
      id: azure
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation Cloud Volumes ONTAP
    url: "/index.html"
  - title: Notes de version
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limitations connues
      url: "/reference-limitations.html"
    - title: Notes de version de Cloud Volumes ONTAP
      url: "/whats-new-ontap.html"
  - title: Commencer
    entries:
    - title: En savoir plus sur Cloud Volumes ONTAP
      url: "/concept-overview-cvo.html"
    - title: Versions ONTAP prises en charge pour les nouveaux déploiements
      url: "/reference-versions.html"
    - title: Démarrer avec Amazon Web Services
      flavor: aws
      entries:
      - title: Démarrage rapide
        url: "/task-getting-started-aws.html"
      - title: Planifiez votre configuration
        url: "/task-planning-your-config.html"
      - title: Configurez votre réseau
        entries:
        - title: Configurer le réseau AWS
          url: "/reference-networking-aws.html"
        - title: Configurer une passerelle de transit AWS
          url: "/task-setting-up-transit-gateway.html"
        - title: Déployer une paire HA dans un sous-réseau partagé
          url: "/task-deploy-aws-shared-vpc.html"
        - title: Configurer Cloud Volumes ONTAP pour la création d'un groupe de placement
            AWS
          url: "/task-configure-placement-group-failure-aws.html"
        - title: Règles de groupe de sécurité pour AWS
          url: "/reference-security-groups.html"
      - title: Configurer AWS KMS
        url: "/task-setting-up-kms.html"
      - title: Configurer les rôles IAM
        url: "/task-set-up-iam-roles.html"
      - title: Configurer les licences
        url: "/task-set-up-licensing-aws.html"
      - title: Utiliser la méthode de déploiement rapide pour Cloud Volumes ONTAP
          dans AWS
        url: "/task-quick-deploy-aws.html"
      - title: Utiliser la méthode de déploiement avancée pour Cloud Volumes ONTAP
          dans AWS
        url: "/task-deploying-otc-aws.html"
      - title: Déployer Cloud Volumes ONTAP dans les régions secrètes AWS
        url: "/task-getting-started-aws-c2s.html"
    - title: Démarrer avec Microsoft Azure
      flavor: azure
      entries:
      - title: Découvrez les options de déploiement de Cloud Volumes ONTAP dans Azure
        url: "/concept-azure-mktplace-direct.html"
      - title: Démarrer dans la NetApp Console
        entries:
        - title: Démarrage rapide
          url: "/task-getting-started-azure.html"
        - title: Planifiez votre configuration
          url: "/task-planning-your-config-azure.html"
        - title: Configurez votre réseau
          url: "/reference-networking-azure.html"
        - title: Configurer le cryptage à l'aide de votre clé
          url: "/task-set-up-azure-encryption.html"
        - title: Configurer les licences
          url: "/task-set-up-licensing-azure.html"
        - title: Activer le mode haute disponibilité
          url: "/task-azure-high-availability-mode.html"
        - title: Activer VMOrchestratorZonalMultiFD pour les zones de disponibilité
            uniques
          url: "/task-saz-feature.html"
        - title: Lancer Cloud Volumes ONTAP dans Azure
          url: "/task-deploying-otc-azure.html"
        - title: Vérifier l'image de la plateforme Azure
          entries:
          - title: Aperçu
            url: "/concept-azure-image-verification.html"
          - title: Téléchargez le fichier image Azure
            url: "/task-azure-download-digest-file.html"
          - title: Exporter le fichier image Azure
            url: "/task-azure-image-export.html"
          - title: Vérifier la signature du fichier
            entries:
            - title: En savoir plus sur la vérification de la signature des fichiers
              url: "/concept-azure-file-sig-verify.html"
            - title: Vérifier la signature du fichier sous Linux
              url: "/task-file-verification-linux.html"
            - title: Vérifier la signature du fichier sur macOS
              url: "/task-file-verification-mac.html"
      - title: Démarrez sur le marché
        url: "/task-deploy-cvo-azure-mktplc.html"
    - title: Démarrer avec Google Cloud
      flavor: gcp
      entries:
      - title: Démarrage rapide
        url: "/task-getting-started-gcp.html"
      - title: Planifiez votre configuration
        url: "/task-planning-your-config-gcp.html"
      - title: Configurez votre réseau
        url: "/reference-networking-gcp.html"
      - title: Planifier les contrôles de service VPC
        url: "/reference-vpc-service-controls-gcp.html"
      - title: Créer un compte de service
        url: "/task-creating-gcp-service-account.html"
      - title: Utiliser des clés de chiffrement gérées par le client
        url: "/task-setting-up-gcp-encryption.html"
      - title: Configurer les licences
        url: "/task-set-up-licensing-google.html"
      - title: Lancer Cloud Volumes ONTAP dans Google Cloud
        url: "/task-deploying-gcp.html"
      - title: Vérification d'image de Google Cloud Platform
        entries:
        - title: Aperçu
          url: "/concept-gcp-image-verification.html"
        - title: Convertir une image au format Raw sur GCP
          url: "/task-gcp-convert-image-raw.html"
        - title: Vérification de la signature de l'image
          entries:
          - title: Vérifier les images signées GCP
            url: "/concept-gcp-verify-signed-image.html"
          - title: Vérifier le contenu à l'aide d'OpenSSL
            url: "/task-verify-openssl-gcp.html"
  - title: Utiliser Cloud Volumes ONTAP
    entries:
    - title: Gestion des licences
      entries:
      - title: Gérer les licences basées sur la capacité
        url: "/task-manage-capacity-licenses.html"
      - title: Gérer les abonnements Keystone
        url: "/task-manage-keystone.html"
      - title: Gérer les licences basées sur les nœuds
        url: "/task-manage-node-licenses.html"
    - title: Administration des volumes et des LUN
      entries:
      - title: Créer des volumes
        url: "/task-create-volumes.html"
      - title: Gérer les volumes existants
        url: "/task-manage-volumes.html"
      - title: Hiérarchiser les données inactives vers le stockage d'objets
        url: "/task-tiering.html"
      - title: Connecter un LUN à un hôte
        url: "/task-connect-lun.html"
      - title: Accélérez l'accès aux données avec FlexCache
        url: "/task-accelerate-data-access.html"
    - title: Administration globale
      entries:
      - title: Créer des agrégats
        url: "/task-create-aggregates.html"
      - title: Gérer les agrégats existants
        url: "/task-manage-aggregates.html"
      - title: Gérer les paramètres de capacité
        url: "/task-manage-capacity-settings.html"
    - title: Administration des machines virtuelles de stockage
      entries:
      - title: Travailler avec des machines virtuelles de stockage
        url: "/task-managing-svms.html"
      - title: Gérer les machines virtuelles de stockage dans AWS
        flavor: aws
        url: "/task-managing-svms-aws.html"
      - title: Gérer les machines virtuelles de stockage dans Azure
        flavor: azure
        url: "/task-managing-svms-azure.html"
      - title: Gérer les machines virtuelles de stockage dans Google Cloud
        flavor: gcp
        url: "/task-managing-svms-gcp.html"
      - title: Configurer la récupération après sinistre SVM
        url: "/task-manage-svm-dr.html"
    - title: Sécurité et cryptage des données
      entries:
      - title: Chiffrer les volumes avec le chiffrement NetApp
        url: "/task-encrypting-volumes.html"
      - title: Gérer les clés avec AWS Key Management Service
        flavor: aws
        url: "/task-aws-key-management.html"
      - title: Gérer les clés avec Azure Key Vault
        flavor: azure
        url: "/task-azure-key-vault.html"
      - title: Gérer les clés avec Google Cloud KMS
        flavor: gcp
        url: "/task-google-key-manager.html"
      - title: Améliorer la protection contre les ransomwares
        url: "/task-protecting-ransomware.html"
      - title: Créer des copies instantanées inviolables pour le stockage WORM
        url: "/reference-worm-snaplock.html"
    - title: Administration du système
      entries:
      - title: Mettre à niveau Cloud Volumes ONTAP
        url: "/task-updating-ontap-cloud.html"
      - title: Enregistrer les systèmes de paiement à l'utilisation
        url: "/task-registering.html"
      - title: Convertir les licences basées sur les nœuds
        url: "/task-convert-node-capacity.html"
      - title: Arrêter et démarrer un système
        url: "/task-managing-state.html"
      - title: Synchroniser l'heure du système
        url: "/task-sync-time.html"
      - title: Modifier la vitesse d'écriture du système
        url: "/task-modify-write-speed.html"
      - title: Changer le mot de passe du système
        url: "/task-change-password.html"
      - title: Ajouter, supprimer ou supprimer des systèmes
        entries:
        - title: Ajouter un système existant
          url: "/task-adding-systems.html"
        - title: Supprimer un système
          url: "/task-removing.html"
        - title: Supprimer un système
          url: "/task-deleting-system.html"
      - title: Administration AWS
        flavor: aws
        entries:
        - title: Travailler avec des instances EC2 dans AWS
          url: "/task-change-ec2-instance.html"
        - title: Modifier les tables de routage pour les paires HA
          url: "/task-change-route-tables.html"
        - title: Configurer la création d'un groupe de placement
          url: task-configure-placement-group-failure-aws.html
      - title: Administration Azure
        flavor: azure
        entries:
        - title: Modifier le type de machine virtuelle Azure
          url: "/task-change-azure-vm.html"
        - title: Remplacer les verrous CIFS
          url: "/task-overriding-cifs-locks.html"
        - title: Utiliser un lien privé Azure ou des points de terminaison de service
          url: "/task-enabling-private-link.html"
        - title: Déplacer les groupes de ressources
          url: "/task-moving-resource-groups-azure.html"
        - title: Séparer le trafic SnapMirror dans Azure
          url: "/task-segregate-snapmirror-azure.html"
      - title: Administration de Google Cloud
        flavor: gcp
        entries:
        - title: Changer le type de machine
          url: "/task-change-gcp-machine.html"
      - title: Administration depuis le gestionnaire système
        url: "/task-administer-advanced-view.html"
      - title: Administration depuis la CLI
        url: "/task-connecting-to-otc.html"
    - title: Santé et événements du système
      entries:
      - title: Vérifier la configuration AutoSupport
        url: "/task-verify-autosupport.html"
      - title: Configurer EMS
        url: "/task-configure-ems.html"
  - title: Concepts
    entries:
    - title: Licences
      entries:
      - title: Licences dans Cloud Volumes ONTAP
        url: "/concept-licensing.html"
      - title: En savoir plus sur les licences basées sur la capacité
        url: "/concept-licensing-charging.html"
    - title: Stockage
      entries:
      - title: Protocoles clients
        url: "/concept-client-protocols.html"
      - title: Disques et agrégats
        url: "/concept-storage.html"
      - title: Volumes élastiques dans AWS
        flavor: aws
        url: "/concept-aws-elastic-volumes.html"
      - title: hiérarchisation des données
        url: "/concept-data-tiering.html"
      - title: Gestion du stockage
        url: "/concept-storage-management.html"
      - title: Vitesse d'écriture
        url: "/concept-write-speed.html"
      - title: Cache Flash
        url: "/concept-flash-cache.html"
      - title: Stockage de l'WORM
        url: "/concept-worm.html"
    - title: Paires à haute disponibilité
      entries:
      - title: Paires HA dans AWS
        flavor: aws
        url: "/concept-ha.html"
      - title: Paires HA dans Azure
        flavor: azure
        url: "/concept-ha-azure.html"
      - title: Paires HA dans GCP
        flavor: gcp
        url: "/concept-ha-google-cloud.html"
      - title: Actions lors de la prise de contrôle du stockage
        url: "/concept-degraded-ha-pair.html"
    - title: Sécurité
      url: "/concept-security.html"
    - title: Performances
      url: "/concept-performance.html"
    - title: Gestion du BYOL basé sur les nœuds
      url: "/concept-license-management.html"
    - title: AutoSupport et Digital Advisor
      url: "/concept-active-iq.html"
    - title: Configurations par défaut
      url: "/reference-default-configs.html"
  - title: Connaissances et soutien
    entries:
    - title: Inscrivez-vous pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenir de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
