---
sidebar: sidebar 
permalink: reference-versions.html 
keywords: versions, supported versions, new versions, cloud volumes ontap version 
summary: La NetApp Console vous permet de choisir parmi plusieurs versions ONTAP différentes lorsque vous créez un nouveau système Cloud Volumes ONTAP . 
---
= Versions ONTAP prises en charge pour les déploiements Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console vous permet de choisir parmi plusieurs versions ONTAP différentes lorsque vous ajoutez un système Cloud Volumes ONTAP .

Les versions de Cloud Volumes ONTAP autres que celles listées ici ne sont pas disponibles pour les nouveaux déploiements. Le correctif ou la version générique (General Availability) d'une version ici représente la version de base disponible pour le déploiement. Pour plus d'informations sur les correctifs disponibles, consultez la  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-new.html["notes de version avec gestion des versions"^] pour chaque version.

Pour plus d'informations sur la mise à niveau, consultez link:task-updating-ontap-cloud.html#supported-upgrade-paths["Chemins de mise à niveau pris en charge"].

ifdef::aws[]



[[aws]]
== AWS

Nœud unique::
+
--
* 9.19.1
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9,7 P5
* 9,5 P6


--
paire HA::
+
--
* 9.19.1
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9,7 P5
* 9,5 P6


--


endif::aws[]

ifdef::azure[]



[[azure]]
== Azuré

Nœud unique::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--
paire HA::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--


endif::azure[]

ifdef::gcp[]



[[google-cloud]]
== Google Cloud

Nœud unique::
+
--
* 9.19.1
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9,7 P5


--
paire HA::
+
--
* 9.19.1
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8


--


endif::gcp[]
