---
sidebar: sidebar 
permalink: task-getting-started-azure.html 
keywords: microsoft, azure, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, marketplace, virtual machine, vnet, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, permissions, custom role, role, json, permissions, virtual machine, connectivity, internet, outbound, endpoint, connection, networks, vpn, replicating, policy, iam, setupasservice, sign up, cloud manager, BlueXP, cloud volumes ontap, cloud ontap, subscription, create 
summary: Démarrez avec Cloud Volumes ONTAP pour Azure en quelques étapes. 
---
= Présentation du déploiement de Cloud Volumes ONTAP dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour déployer Cloud Volumes ONTAP, vous devez d'abord connaître votre abonnement Azure et vos licences Cloud Volumes ONTAP. Vous devez également vérifier que vous disposez d'un agent NetApp Console créé pour votre abonnement Azure et votre organisation. Vous devez effectuer la majeure partie des étapes de cette rubrique dans le cadre de la configuration de votre Console avant même de commencer à déployer Cloud Volumes ONTAP.

[cols="20,35,25,25"]
|===
| Tâche | Description | Référence | Remarques concernant les déploiements en mode privé 


 a| 
Créer un agent de Console
 a| 
Si vous ne disposez pas encore d'un agent Console, créez-en un avant de déployer Cloud Volumes ONTAP.
 a| 
Consultez le guide d'installation de la console :https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Créez un agent de console dans Azure"^]
 a| 
En cas de déploiement sur un sous-réseau sans accès Internet, installez manuellement l’agent Console et accédez à l’interface utilisateur NetApp Console qui s’exécute sur cet agent Console. Consultez le guide d’installation de la Console : https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Installez manuellement l’agent Console sans accès à Internet"^]



 a| 
Planifiez votre configuration
 a| 
La console propose des packages préconfigurés qui correspondent à vos exigences de charge de travail, ou vous pouvez créer votre propre configuration.  Si vous choisissez votre propre configuration, vous devez comprendre les options qui s’offrent à vous.
 a| 
link:task-planning-your-config-azure.html["Planifiez votre configuration Cloud Volumes ONTAP dans Azure"]
 a| 
Vous devez avoir des considérations de planification similaires pour les déploiements en mode privé.



 a| 
Configurez votre réseau
 a| 
. Assurez-vous que votre VNet et vos sous-réseaux prennent en charge la connectivité entre l'agent NetApp Console et Cloud Volumes ONTAP.
. Activez l'accès Internet sortant depuis le réseau virtuel cible pour NetApp AutoSupport.

 a| 
link:reference-networking-azure.html["Exigences réseau pour Azure"]
 a| 
L'accès Internet sortant pour AutoSupport n'est pas requis. Toutes les autres exigences réseau restent les mêmes.



 a| 
Déployez Cloud Volumes ONTAP depuis la NetApp Console
 a| 
Une fois toutes les conditions préalables remplies, vous pouvez suivre les étapes de l'assistant pour déployer Cloud Volumes ONTAP dans Azure.
 a| 
Reportez-vous à :

* link:task-quick-deploy-azure.html["Déployez Cloud Volumes ONTAP avec Quick create"]
* link:task-deploying-otc-azure.html["Déployez Cloud Volumes ONTAP à l'aide des options avancées"]

 a| 
Avant de commencer le déploiement, assurez-vous d'avoir acheté une licence Cloud Volumes ONTAP auprès de NetApp. Les déploiements en mode privé nécessitent des licences BYOL par nœud. Les abonnements Marketplace ne sont pas pris en charge pour la facturation de votre utilisation de Cloud Volumes ONTAP. Obtenez le fichier de licence auprès de NetApp et téléchargez-le lors du déploiement. Voir :

* link:concept-license-management.html["Gestion des licences pour BYOL basé sur les nœuds"]
* link:task-manage-node-licenses.html["Gérer les licences BYOL basées sur les nœuds"]
* link:task-quick-deploy-azure.html["Déployez Cloud Volumes ONTAP avec Quick create"]
* link:task-deploying-otc-azure.html["Déployez Cloud Volumes ONTAP à l'aide des options avancées"]


|===
.Liens connexes
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Création d'un agent de console à partir de la console"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-marketplace.html["Création d'un agent de console à partir de la Place de marché Azure"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Installation du logiciel agent de console sur un hôte Linux"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["Ce que fait la console avec les autorisations"^]

