---
sidebar: sidebar 
permalink: task-getting-started-gcp.html 
keywords: google cloud platform, gcp, cloud manager, deploy the Console, launch the Console, create the Console, getting started, networking, gcp networking, service account, tiering, data tiering, bucket, fabricpool, cloud backup, storage access key, gcp role, role, iam role, permissions, gcp permissions, cloud backup, the Console 
summary: Démarrez avec Cloud Volumes ONTAP pour Google Cloud en quelques étapes. 
---
= Présentation du déploiement de Cloud Volumes ONTAP dans Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour déployer Cloud Volumes ONTAP, vous devez d'abord connaître votre abonnement Google Cloud et vos licences Cloud Volumes ONTAP. Vous devez également vérifier que vous disposez d'un agent NetApp Console créé pour votre projet et votre organisation Google Cloud. La plupart des informations de ce sujet doivent être prises en compte lors de la configuration de votre Console, avant même de commencer à déployer Cloud Volumes ONTAP.

[cols="20,35,25,25"]
|===
| Tâche | Description | Référence | Remarques concernant les déploiements en mode privé 


 a| 
Créer un agent de Console
 a| 
Si vous ne disposez pas encore d'un agent Console, créez-en un avant de déployer Cloud Volumes ONTAP. Si le déploiement s'effectue dans un sous-réseau sans accès Internet, installez manuellement l'agent Console et accédez à la NetApp Console exécutée sur cet agent.
 a| 
Consultez le guide d'installation de la console :https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-google-gcloud.html["Créer un agent de console dans Google Cloud"^]
 a| 
En cas de déploiement sur un sous-réseau sans accès Internet, installez manuellement l’agent Console et accédez à l’interface utilisateur NetApp Console qui s’exécute sur cet agent Console. Consultez le guide d’installation de la Console : https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Installez manuellement l’agent Console sans accès à Internet"^]



 a| 
Planifiez votre configuration
 a| 
La console propose des packages préconfigurés qui correspondent à vos exigences de charge de travail, ou vous pouvez créer votre propre configuration.  Si vous choisissez votre propre configuration, vous devez comprendre les options qui s’offrent à vous.
 a| 
link:task-planning-your-config-gcp.html["Planifiez votre configuration"]
 a| 
Vous devez avoir des considérations de planification similaires pour les déploiements en mode privé.



 a| 
Configurez votre réseau
 a| 
. Assurez-vous que votre VPC et vos sous-réseaux prendront en charge la connectivité entre l’agent de console et Cloud Volumes ONTAP.
. Si vous prévoyez d'activer la hiérarchisation des données, configurez le sous-réseau Cloud Volumes ONTAP pour Private Google Access.
. Si vous déployez une paire HA, assurez-vous de disposer de quatre VPC, chacun avec son propre sous-réseau.
. Si vous utilisez un VPC partagé, attribuez le rôle _Compute Network User_ au compte de service de l’agent de la console.
. Activez l'accès Internet sortant à partir du VPC cible pour NetApp AutoSupport.

 a| 
Reportez-vous à :

* link:reference-networking-gcp.html["Exigences réseau pour Google Cloud"]
* Consultez la documentation Google Cloud : https://cloud.google.com/vpc/docs/configure-private-google-access["Configurer Private Google Access"^]

 a| 
L'accès Internet sortant pour AutoSupport n'est pas requis. Toutes les autres exigences réseau restent les mêmes.



 a| 
Créer un compte de service
 a| 
Cloud Volumes ONTAP nécessite un compte de service Google Cloud pour activer la hiérarchisation des données afin de transférer les données froides vers un stockage d'objets à faible coût sur Google Cloud, et également pour activer NetApp Backup and Recovery afin de sauvegarder les volumes dans un stockage d'objets à faible coût.
 a| 
* link:task-creating-gcp-service-account.html["Créer un compte de service"]
* link:concept-data-tiering.html["Découvrez la hiérarchisation des données"]
* Consultez la  https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["Documents NetApp Backup and Recovery"^]

 a| 
Aucune considération supplémentaire pour les déploiements en mode privé.



 a| 
Activer les API Google Cloud
 a| 
Activez les API Google Cloud requises dans votre projet. Vous les avez peut-être déjà activées lors de la création de l'agent Console.
 a| 
Consultez la documentation Google Cloud :https://cloud.google.com/apis/docs/getting-started#enabling_apis["Activer les API Google Cloud"^]
 a| 
Les API doivent être activées. Collaborez avec votre administrateur cloud pour activer les API requises dans votre environnement privé.



 a| 
Déployez Cloud Volumes ONTAP depuis la NetApp Console
 a| 
Une fois toutes les conditions préalables remplies, vous pouvez suivre les étapes de l'assistant pour déployer Cloud Volumes ONTAP dans Google Cloud.
 a| 
Reportez-vous à :

* link:task-quick-deploy-gcp.html["Déployez Cloud Volumes ONTAP avec Quick create"]
* link:task-deploying-gcp.html["Déployez Cloud Volumes ONTAP à l'aide des options avancées"]

 a| 
Avant de commencer le déploiement, assurez-vous d'avoir acheté une licence Cloud Volumes ONTAP auprès de NetApp. Les déploiements en mode privé nécessitent des licences BYOL par nœud. Les abonnements Marketplace ne sont pas pris en charge pour la facturation de votre utilisation de Cloud Volumes ONTAP. Obtenez le fichier de licence auprès de NetApp et téléchargez-le lors du déploiement. Voir :

* link:concept-license-management.html["Gestion des licences pour BYOL basé sur les nœuds"]
* link:task-manage-node-licenses.html["Gérer les licences BYOL basées sur les nœuds"]
* link:task-quick-deploy-gcp.html["Déployez Cloud Volumes ONTAP avec Quick create"]
* link:task-deploying-gcp.html["Déployez Cloud Volumes ONTAP à l'aide des options avancées"]


|===
.Liens connexes
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Création d'un agent de console"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Installation du logiciel agent de console sur un hôte Linux"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["Autorisations Google Cloud pour l'agent de la console"^]

