---
sidebar: sidebar 
permalink: task-setting-up-gcp-encryption.html 
keywords: encryption, gcp, encryption key, permissions, customer-managed, gcpencryption 
summary: Bien que Google Cloud Storage chiffre toujours vos données avant de les écrire sur le disque, vous pouvez utiliser les API de la console pour créer un système Cloud Volumes ONTAP qui utilise des clés de chiffrement gérées par le client.  Il s’agit de clés que vous générez et gérez dans GCP à l’aide du service Cloud Key Management. 
---
= Utilisation de clés de chiffrement gérées par le client avec Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bien que Google Cloud Storage chiffre toujours vos données avant qu'elles ne soient écrites sur le disque, vous pouvez utiliser les API pour créer un système Cloud Volumes ONTAP qui utilise des _clés de chiffrement gérées par le client_.  Il s’agit de clés que vous générez et gérez dans GCP à l’aide du service Cloud Key Management.

.Étapes
. Assurez-vous que le compte de service de l’agent de console dispose des autorisations appropriées au niveau du projet, dans le projet où la clé est stockée.
+
Les autorisations sont fournies dans le https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["les autorisations du compte de service par défaut"^] , mais peut ne pas être appliqué si vous utilisez un autre projet pour le service Cloud Key Management.

+
Les autorisations sont les suivantes :

+
[source, yaml]
----
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
----
. Assurez-vous que le compte de service pour le https://cloud.google.com/iam/docs/service-agents["Agent de service Google Compute Engine"^] dispose des autorisations Cloud KMS Encrypter/Decrypter sur la clé.
+
Le nom du compte de service utilise le format suivant : « service-[numéro_de_projet_service]@compute-system.iam.gserviceaccount.com ».

+
https://cloud.google.com/kms/docs/iam#granting_roles_on_a_resource["Documentation Google Cloud : Utilisation d'IAM avec Cloud KMS – Attribution de rôles sur une ressource"]

. Obtenez l'« id » de la clé en appelant la commande get pour le `/gcp/vsa/metadata/gcp-encryption-keys` Appel d'API ou en choisissant « Copier le nom de la ressource » sur la clé dans la console GCP.
. Si vous utilisez des clés de chiffrement gérées par le client et que vous hiérarchisez les données vers le stockage d'objets, la NetApp Console tente d'utiliser les mêmes clés que celles utilisées pour chiffrer les disques persistants.  Mais vous devrez d’abord activer les buckets Google Cloud Storage pour utiliser les clés :
+
.. Recherchez l'agent de service Google Cloud Storage en suivant les instructions https://cloud.google.com/storage/docs/getting-service-agent["Documentation Google Cloud : Obtenir l'agent de service Cloud Storage"^] .
.. Accédez à la clé de chiffrement et attribuez à l’agent de service Google Cloud Storage les autorisations Cloud KMS Encrypter/Decrypter.


+
Pour plus d'informations, reportez-vous à https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys["Documentation Google Cloud : Utilisation des clés de chiffrement gérées par le client"^]

. Utilisez le paramètre « GcpEncryption » avec votre requête API lors de la création d'un système.
+
*Exemple*

+
[source, json]
----
"gcpEncryptionParameters": {
    "key": "projects/project-1/locations/us-east4/keyRings/keyring-1/cryptoKeys/generatedkey1"
  }
----


Reportez-vous à la https://docs.netapp.com/us-en/bluexp-automation/index.html["Documentation sur l'automatisation de la NetApp Console"^] pour plus de détails sur l'utilisation du paramètre « GcpEncryption ».
