---
sidebar: sidebar 
permalink: task-sync-time.html 
keywords: set up, setting up, ntp, time, synch 
summary: La spécification d’un serveur NTP synchronise l’heure entre les systèmes de votre réseau, ce qui peut aider à éviter les problèmes dus aux différences d’heure. 
---
= Synchroniser l'heure système de Cloud Volumes ONTAP à l'aide de serveurs NTP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La configuration des serveurs Network Time Protocol (NTP) pour vos clusters Cloud Volumes ONTAP garantit une synchronisation précise de l'heure de votre cluster avec les autres systèmes de votre réseau et les serveurs externes. La synchronisation de l'heure de votre cluster avec des serveurs NTP externes contribue à maintenir la cohérence de votre infrastructure. NetApp configure par défaut des serveurs NTP pour les nouveaux déploiements Cloud Volumes ONTAP. Cependant, s'ils ne sont pas configurés pour vos clusters Cloud Volumes ONTAP existants, vous devez configurer des serveurs NTP pour une synchronisation précise de l'heure à l'intérieur et à l'extérieur de votre réseau.

Vous pouvez spécifier un serveur NTP en utilisant :

* https://docs.netapp.com/us-en/bluexp-automation/cm/api_ref_resources.html["L'API de la NetApp Console"^].
* La commande CLI ONTAP https://docs.netapp.com/us-en/ontap-cli//cluster-time-service-ntp-server-create.html["serveur NTP de service de temps de cluster créer"^].



NOTE: Si vous ne configurez pas de serveur NTP, vous risquez de subir des interruptions de service et une synchronisation horaire inexacte.

.Liens connexes
* Article de la base de connaissances (KB) : https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs/How_does_a_CVO_cluster_use_NTP["Comment un cluster CVO utilise-t-il NTP ?"]
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["Préparez-vous à utiliser l'API"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Flux de travail Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/get_identifiers.html#get-the-connector-identifier["Obtenir les identifiants requis"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/use_rest_apis.html["Utiliser les API REST pour la NetApp Console"^]

