---
sidebar: sidebar 
permalink: task-connect-lun.html 
keywords: lun, connect lun, iscsi lun, target iqn, iqn 
summary: 'Lorsque vous créez un volume iSCSI, la console NetApp crée automatiquement un LUN pour vous.  Nous avons simplifié les choses en créant un seul LUN par volume, il n"y a donc aucune gestion impliquée.  Après avoir créé le volume, utilisez l’IQN pour vous connecter au LUN à partir de vos hôtes.' 
---
= Connectez-vous à un LUN sur Cloud Volumes ONTAP depuis votre système hôte
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous créez un volume iSCSI, la console NetApp crée automatiquement un LUN pour vous.  Nous avons simplifié les choses en créant un seul LUN par volume, il n'y a donc aucune gestion impliquée.  Après avoir créé le volume, utilisez l’IQN pour vous connecter au LUN à partir de vos hôtes.

Notez ce qui suit :

* La gestion automatique de la capacité de la console ne s'applique pas aux LUN.  Lorsqu'il crée un LUN, il désactive la fonction de croissance automatique.
* Vous pouvez créer des LUN supplémentaires à partir d' ONTAP System Manager ou de l' ONTAP CLI.


.Étapes
. Dans le menu de navigation de gauche, sélectionnez *Stockage > Gestion*.
. Sur la page *Systèmes*, double-cliquez sur le système Cloud Volumes ONTAP sur lequel vous souhaitez gérer les volumes.
. Dans le système, sélectionnez l’onglet *Volumes*.
. Accédez à la mosaïque de volume requise, puis sélectionnez *Gérer le volume* pour accéder au panneau Gérer les volumes sur la droite.
. Cliquez sur *Cible iQN*.
. Cliquez sur *Copier* pour copier le nom iQN.
. Configurez une connexion iSCSI de l’hôte au LUN.
+
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/GUID-15E8C226-BED5-46D0-BAED-379EA4311340.html["Configuration express iSCSI ONTAP 9 pour Red Hat Enterprise Linux : démarrage des sessions iSCSI avec la cible"^]
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-cpg/GUID-857453EC-90E9-4AB6-B543-83827CF374BF.html["Configuration express iSCSI ONTAP 9 pour Windows : démarrage de sessions iSCSI avec la cible"^]
** https://docs.netapp.com/us-en/ontap-sanhost/["Configuration de l'hôte SAN ONTAP"^]



