---
sidebar: sidebar 
permalink: task-deploy-cvo-azure-mktplc.html 
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace 
summary:  
---
= Déployez Cloud Volumes ONTAP depuis la Place de marché Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser le déploiement direct depuis Azure Marketplace pour déployer rapidement et facilement Cloud Volumes ONTAP. Depuis Azure Marketplace, vous pouvez déployer rapidement Cloud Volumes ONTAP en quelques clics et explorer ses principales fonctionnalités et capacités dans votre environnement.

Pour plus d'informations sur cette offre, reportez-vous àlink:concept-azure-mktplace-direct.html["Découvrez les offres Cloud Volumes ONTAP dans la NetApp Console et sur la place de marché"] .

.À propos de cette tâche
Le système Cloud Volumes ONTAP déployé via le déploiement direct d'Azure Marketplace possède les propriétés suivantes. Notez que les fonctionnalités d'une instance autonome déployée via Azure Marketplace changent lorsqu'elle est découverte dans la NetApp Console.

* La dernière version de Cloud Volumes ONTAP (9.16.1 ou ultérieure).
* Une licence gratuite pour Cloud Volumes ONTAP est fournie pour une capacité provisionnée allant jusqu'à 500 Gio, sans support NetApp et sans date d'expiration. Une capacité supérieure à 500 Gio nécessite un droit de licence valide et peut entraîner des frais. Pour accéder à l'expérience complète Cloud Volumes ONTAP et aux fonctionnalités avancées de gestion, connectez votre système Cloud Volumes ONTAP à la NetApp Console. La découverte et la gestion via la NetApp Console nécessitent un abonnement Azure Marketplace valide associé à votre compte NetApp Console.
* Deux nœuds configurés en mode haute disponibilité (HA) dans une seule zone de disponibilité (AZ), provisionnés avec des numéros de série par défaut.  Les machines virtuelles de stockage (VM de stockage) sont déployées dans unlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["mode d'orchestration flexible"] .
* Un agrégat pour l'instance créée par défaut.
* Un disque géré SSD v2 Premium d'une capacité provisionnée de 500 Gio, ainsi qu'un disque racine et un disque de données.
* Une machine virtuelle de stockage de données déployée, avec des services de données NFS, CIFS, iSCSI et NVMe/TCP.  Vous ne pouvez pas ajouter de machines virtuelles de stockage de données supplémentaires.
* Licences installées pour NFS, CIFS (SMB), iSCSI, Autonomous Ransomware Protection (ARP), SnapLock et SnapMirror.
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["Efficacité du stockage sensible à la température ONTAP (TSSE)"^], chiffrement du volume et gestion des clés externes activés par défaut.
* Ces fonctionnalités ne sont pas prises en charge :
+
** Hiérarchisation de FabricPool
** Modification du type de machine virtuelle de stockage
** Mode d'écriture rapide




.Avant de commencer
* Si vous prévoyez de découvrir et de gérer le système déployé dans la NetApp Console, assurez-vous que le compte NetApp Console est associé à un abonnement valide sur Azure Marketplace. La découverte du système dans la NetApp Console nécessite un abonnement valide.
* Assurez-vous de répondre aux exigences de mise en réseau pour unlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["Déploiement HA dans une seule zone de disponibilité"] dans Azure. link:reference-networking-azure.html["Configurer la mise en réseau Azure pour Cloud Volumes ONTAP"] .
* L'un de ces rôles Azure doit vous être attribué pour déployer Cloud Volumes ONTAP:
+
** Le `contributor` rôle avec les autorisations par défaut. Pour plus d'informations, reportez-vous à la https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Documentation Microsoft Azure : rôles intégrés Azure"^] .
** Un rôle RBAC personnalisé avec les autorisations suivantes. Pour plus d'informations, reportez-vous à la https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles["Documentation Azure : rôles personnalisés Azure"^] .
+
[]
====
"permissions": [ { "actions": [ "Microsoft.AAD/register/action", "Microsoft.Resources/subscriptions/resourceGroups/write", "Microsoft.Network/loadBalancers/write", "Microsoft.ClassicCompute/virtualMachines/write", "Microsoft.Compute/capacityReservationGroups/deploy/action", "Microsoft.ClassicCompute/virtualMachines/networkInterfaces/associatedNetworkSecurityGroups/write", "Microsoft.Network/networkInterfaces/write", "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/extensions/write", "Microsoft.Resources/deployments/validate/action", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Network/virtualNetworks/write", "Microsoft.Network/virtualNetworks/read", "Microsoft.Network/networkSecurityGroups/write", "Microsoft.Network/networkSecurityGroups/read", "Microsoft.Compute/disks/write", "Microsoft.Compute/virtualMachineScaleSets/write", "Microsoft.Resources/deployments/write", "Microsoft.Network/virtualNetworks/subnets/read", "Microsoft.Network/virtualNetworks/subnets/write" ], "notActions": [], "dataActions": [], "notDataActions": [] } ]

====
+

NOTE: Si vous avez enregistré le fournisseur de ressources « Microsoft.storage » dans votre abonnement, vous n'avez pas besoin du `Microsoft.AAD/register/action` autorisation. Pour plus d'informations, reportez-vous à la https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage["Documentation Azure : autorisations Azure pour le stockage"^] .





.Étapes
. Sur le site Azure Marketplace, recherchez des produits NetApp.
. Sélectionnez * NetApp Cloud Volumes ONTAP direct*.
. Cliquez sur *Créer* pour lancer l’assistant de déploiement.
. Sélectionnez un plan.  La liste *Plan* affiche généralement les dernières versions de Cloud Volumes ONTAP.
. Dans l'onglet *Bases*, fournissez les détails suivants :
+
** *Abonnement* : Sélectionnez un abonnement.  Le déploiement sera lié au numéro d'abonnement.
** *Groupe de ressources* : utilisez un groupe de ressources existant ou créez-en un nouveau.  Les groupes de ressources aident à allouer toutes les ressources, telles que les disques et les machines virtuelles de stockage, au sein d'un seul groupe pour un système Cloud Volumes ONTAP .
** *Région* : sélectionnez une région qui prend en charge le déploiement d’Azure HA dans une seule zone de disponibilité.  Vous ne voyez que les régions disponibles dans la liste.
** *Taille* : sélectionnez une taille de machine virtuelle de stockage pour le disque géré SSD Premium v2 pris en charge.
** *Zone* : sélectionnez une zone pour la région que vous avez sélectionnée.
** *Mot de passe administrateur* : définissez un mot de passe.  Vous utilisez ce mot de passe administrateur pour vous connecter au système après le déploiement.
** *Confirmer le mot de passe* : saisissez à nouveau le même mot de passe pour confirmation.
+
*** Dans l'onglet *Réseau*, ajoutez un réseau virtuel et un sous-réseau, ou sélectionnez-les dans les listes.
+

NOTE: Pour respecter les restrictions de Microsoft Azure, vous devez créer un nouveau sous-réseau lors de la configuration d’un nouveau réseau virtuel.  De même, si vous choisissez un réseau existant, vous devez sélectionner un sous-réseau existant.

*** Pour sélectionner un groupe de sécurité réseau prédéfini, sélectionnez *Oui*.  Sélectionnez *Non* pour attribuer un groupe de sécurité réseau Azure prédéfini avec les règles de trafic nécessaires. Pour plus d'informations, reportez-vous à link:reference-networking-azure.html#security-group-rules["Règles de groupe de sécurité pour Azure"] .
*** Dans l’onglet *Avancé*, confirmez si les deux fonctionnalités Azure nécessaires à ce déploiement ont été définies. Se référer àlink:task-saz-feature.html["Activer une fonctionnalité Azure pour les déploiements Cloud Volumes ONTAP à zone de disponibilité unique"] etlink:task-azure-high-availability-mode.html["Activer le mode haute disponibilité pour Cloud Volumes ONTAP dans Azure"] .
*** Vous pouvez définir des paires nom et valeur pour les ressources ou les groupes de ressources dans l'onglet *Tags*.
*** Dans l’onglet *Réviser + créer*, vérifiez les détails et démarrez le déploiement.






.Après avoir terminé
Sélectionnez l’icône de notification pour afficher la progression de votre déploiement.  Une fois Cloud Volumes ONTAP déployé, vous pouvez afficher la machine virtuelle de stockage répertoriée pour les opérations.

Une fois accessible, utilisez ONTAP System Manager ou ONTAP CLI pour vous connecter à la machine virtuelle de stockage avec les informations d'identification d'administrateur que vous avez définies.  Par la suite, vous pouvez créer des volumes, des LUN ou des partages et commencer à utiliser les capacités de stockage de Cloud Volumes ONTAP.



[[troubleshoot-deployment-issues]]
== Résoudre les problèmes de déploiement

Les systèmes Cloud Volumes ONTAP déployés directement via Azure Marketplace ne bénéficient pas du support de NetApp. En cas de problème lors du déploiement, vous pouvez effectuer un dépannage et une résolution indépendants.

.Étapes
. Sur le site Azure Marketplace, accédez à *Diagnostics de démarrage > Journal série*.
. Téléchargez et examinez les journaux série.
. Consultez la documentation du produit et les articles de la base de connaissances (KB) pour le dépannage.
+
** https://learn.microsoft.com/en-us/partner-center/["Documentation Azure Marketplace"]
** https://www.netapp.com/support-and-training/documentation/["Documentation NetApp"]
** https://kb.netapp.com/["Articles de la base de connaissances NetApp"]






[[discover-the-deployed-systems-in-console]]
== Découvrez les systèmes déployés dans la console

Vous pouvez découvrir les systèmes Cloud Volumes ONTAP que vous avez déployés à l'aide du déploiement direct via Azure Marketplace et les gérer sur la page *Systèmes* dans la Console. L'agent de la Console découvre les systèmes, les ajoute, applique les licences nécessaires et débloque toutes les fonctionnalités de la Console pour ces systèmes. La configuration HA d'origine dans une seule AZ avec des disques managés PSSD v2 est conservée, et le système est enregistré sur le même abonnement Azure et dans le même groupe de ressources que le déploiement d'origine.

.À propos de cette tâche
Lors de la découverte des systèmes Cloud Volumes ONTAP déployés à l'aide du déploiement direct via Azure Marketplace, l'agent de la Console effectue les tâches suivantes :

* Remplace les licences gratuites des systèmes découverts par des licences standard basées sur la capacitélink:concept-licensing.html#packages["Licences Freemium"] .
* Conserve les capacités existantes des systèmes déployés et ajoute les capacités supplémentaires de la console, telles que la protection des données, la gestion des données et les fonctionnalités de sécurité.
* Remplace les licences installées sur les nœuds par de nouvelles licences ONTAP pour NFS, CIFS (SMB), iSCSI, ARP, SnapLock et SnapMirror.
* Convertit les numéros de série des nœuds génériques en numéros de série uniques.
* Attribue de nouvelles balises système aux ressources selon les besoins.
* Convertit les adresses IP dynamiques de l'instance en adresses IP statiques.
* Permet les fonctionnalités delink:task-tiering.html["Hiérarchisation de FabricPool"] ,link:task-verify-autosupport.html["AutoSupport"] , etlink:concept-worm.html["écriture unique et lecture multiple"] Stockage (WORM) sur les systèmes déployés.  Vous pouvez activer ces fonctionnalités depuis la console lorsque vous en avez besoin.
* Enregistre les instances sur les comptes NSS utilisés pour les découvrir.
* Active les fonctionnalités de gestion de la capacité danslink:concept-storage-management.html#capacity-management["modes automatique et manuel"] pour les systèmes découverts.


.Avant de commencer
Assurez-vous que le déploiement est terminé sur Azure Marketplace. L’agent de la Console ne peut découvrir les systèmes que lorsque le déploiement est terminé et que ces systèmes sont disponibles pour la découverte.

.Étapes
Dans la console, vous suivez la procédure standard pour découvrir les systèmes existants. link:task-adding-systems.html["Ajouter un système Cloud Volumes ONTAP existant à la console"] .


CAUTION: Lors de la découverte, des messages d'erreur peuvent s'afficher, mais vous pouvez les ignorer jusqu'à la fin du processus de découverte. Ne modifiez pas les configurations Cloud Volumes ONTAP générées par le système dans le portail Azure Marketplace pendant la découverte, en particulier les balises système. Toute modification apportée à ces configurations peut entraîner un comportement inattendu du système.

.Après avoir terminé
Une fois la découverte terminée, vous pouvez afficher les systèmes répertoriés sur la page *Systèmes* de la console.  Vous pouvez effectuer diverses tâches de gestion, telles quelink:task-manage-aggregates.html["élargir l'agrégat"] ,link:task-create-volumes.html["ajout de volumes"] ,link:task-managing-svms-azure.html["provisionnement de machines virtuelles de stockage supplémentaires"] , etlink:task-change-azure-vm.html["changer les types d'instances"] .

.Liens connexes
Reportez-vous à la documentation ONTAP pour plus d'informations sur la création de stockage :

* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-subscriptions.html["Ajouter un nouvel abonnement à la place de marché"^]
* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["Créer des volumes pour NFS"^]
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html["Créer des LUN pour iSCSI"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["Créer des partages pour CIFS"^]

