---
sidebar: sidebar 
permalink: task-file-verification-mac.html 
keywords: Azure, image, VHD, file signature verification, encryption, sha256, ONTAP, Cloud Volumes, CLI, macOS 
summary: 'Vérifier la signature d"un fichier VHD exporté via l"outil de fichier de résumé d"image Cloud Volumes ONTAP sur macOS' 
---
= Vérifier la signature de l'image de la place de marché Azure pour Cloud Volumes ONTAP sur macOS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La vérification d’une signature de fichier VHD exportée sous Linux comprend la validation de la chaîne de confiance, la modification du fichier et la vérification de la signature.

.Étapes
. Téléchargez le fichier image Azure à partir du https://mysupport.netapp.com/site/["Site de support NetApp"^] et extrayez le fichier digest (.sig), le fichier de certificat de clé publique (.pem) et le fichier de certificat de chaîne (.pem).
+
Se référer à https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-azure-download-digest-file.html["Téléchargez le fichier de résumé de l'image Azure"^] pour plus d'informations.

. Vérifier la chaîne de confiance.
+
[source, cli]
----
% openssl verify -CAfile Certificate-Chain-9.15.0P1_azure.pem Certificate-9.15.0P1_azure.pem
Certificate-9.15.0P1_azure.pem: OK
----
. Supprimez 1 Mo (1 048 576 octets) au début et 512 octets à la fin du fichier VHD.  Lors de l'utilisation `tail` , le `-c +K` l'option génère des octets à partir du K-ième octet du fichier.  Par conséquent, il passe 1048577 à `tail -c` .  Notez que sur macOS, l’exécution de la commande tail peut prendre environ dix minutes.
+
[source, cli]
----
% tail -c +1048577 ./9150.01000024.05090105.vhd > ./sign.tmp.tail
% head -c -512 ./sign.tmp.tail > sign.tmp
% rm ./sign.tmp.tail
----
. Utilisez OpenSSL pour extraire la clé publique du certificat et vérifiez le fichier dépouillé (sign.tmp) avec le fichier de signature et la clé publique.  L'invite de commande affiche des messages indiquant la réussite ou l'échec en fonction de la vérification.
+
[source, cli]
----
% openssl x509 -pubkey -noout -in ./Certificate-9.15.0P1_azure.pem > ./Code-Sign-Cert-Public-key.pub

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./sign.tmp
Verified OK

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./another_file_from_nowhere.tmp
Verification Failure
----
. Nettoyer l'espace de travail.
+
[source, cli]
----
% rm ./9150.01000024.05090105.vhd ./sign.tmp
% rm *.sig *.pub *.pem
----

