---
sidebar: sidebar 
permalink: task-change-route-tables.html 
keywords: route tables, update route tables, modify route tables, change route table 
summary: Vous pouvez modifier les tables de routage AWS qui incluent des routes vers les adresses IP flottantes pour une paire HA déployée dans plusieurs zones de disponibilité AWS.  Vous pouvez le faire si de nouveaux clients NFS ou CIFS doivent accéder à une paire HA dans AWS. 
---
= Modifier les tables de routage pour les paires Cloud Volumes ONTAP HA dans plusieurs zones de disponibilité AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez modifier les tables de routage AWS qui incluent des routes vers les adresses IP flottantes pour une paire HA déployée dans plusieurs zones de disponibilité AWS (AZ).  Vous pouvez le faire si de nouveaux clients NFS ou CIFS doivent accéder à une paire HA dans AWS.

.Étapes
. Sur la page *Systèmes*, sélectionnez le système.
. Dans l'onglet Présentation, cliquez sur le panneau Fonctionnalités, puis cliquez sur l'icône en forme de crayon à côté de *Tables de routage*.
. Modifiez la liste des tables de routage sélectionnées, puis cliquez sur *Enregistrer*.


.Résultat
La NetApp Console envoie une requête AWS pour modifier les tables de routage.
