---
sidebar: sidebar 
permalink: task-modify-write-speed.html 
keywords: write speed, high write speed, normal write speed, change write speed 
summary: 'Vous devrez peut-être modifier la configuration des systèmes Cloud Volumes ONTAP à mesure que vos besoins de stockage évoluent.  Par exemple, vous pouvez changer de configuration à la carte, modifier le type d"instance ou de machine virtuelle, et bien plus encore.' 
---
= Modifier la vitesse d'écriture du système
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez choisir une vitesse d'écriture normale ou élevée pour Cloud Volumes ONTAP dans la NetApp Console.  La vitesse d'écriture par défaut est normale.  Vous pouvez passer à une vitesse d'écriture élevée si des performances d'écriture rapides sont requises pour votre charge de travail.

Une vitesse d'écriture élevée est prise en charge avec tous les types de systèmes à nœud unique et certaines configurations de paires HA.  Afficher les configurations prises en charge dans le https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["Notes de version de Cloud Volumes ONTAP"^]

Avant de modifier la vitesse d’écriture, vous devezlink:concept-write-speed.html["comprendre les différences entre les réglages normaux et élevés"] .

.À propos de cette tâche
* Assurez-vous que des opérations telles que la création de volumes ou d’agrégats ne sont pas en cours.
* Sachez que cette modification redémarre le système Cloud Volumes ONTAP .  Il s’agit d’un processus perturbateur qui nécessite un temps d’arrêt pour l’ensemble du système.


.Étapes
. Sur la page *Systèmes*, double-cliquez sur le nom du système que vous configurez pour la vitesse d'écriture.
. Dans l’onglet Présentation, cliquez sur le panneau Fonctionnalités, puis cliquez sur l’icône en forme de crayon à côté de *Vitesse d’écriture*.
. Sélectionnez *Normal* ou *Élevé*.
+
Si vous choisissez Élevé, vous devrez lire la déclaration « Je comprends... » et confirmer en cochant la case.

+

NOTE: L'option de vitesse d'écriture *Élevée* est prise en charge avec les paires Cloud Volumes ONTAP HA dans Google Cloud à partir de la version 9.13.0.

. Cliquez sur *Enregistrer*, vérifiez le message de confirmation, puis cliquez sur *Approuver*.

