= Authentification utilisateur activée pour accéder au Gestionnaire système depuis BlueXP
:allow-uri-read: 




[[user-authentication-enabled-for-accessing-system-manager-from-bluexp]]
=== Authentification utilisateur activée pour accéder au Gestionnaire système depuis BlueXP

En tant qu'administrateur BlueXP , vous pouvez désormais activer l'authentification pour les utilisateurs ONTAP accédant à ONTAP System Manager depuis BlueXP.  Vous pouvez activer cette option en modifiant les paramètres du connecteur BlueXP .  Cette option est disponible pour les modes standard et privé.

link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-administer-advanced-view.html["Administrer Cloud Volumes ONTAP à l'aide de System Manager"^].



[[bluexp-advanced-view-renamed-to-system-manager]]
=== BlueXP Advanced View renommé en Gestionnaire système

L'option de gestion avancée de Cloud Volumes ONTAP depuis BlueXP via ONTAP System Manager a été renommée de *Vue avancée* à *Gestionnaire système*.

link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-administer-advanced-view.html["Administrer Cloud Volumes ONTAP à l'aide de System Manager"^].



[[introducing-a-simpler-way-to-manage-licenses-with-the-bluexp-digital-wallet]]
=== Présentation d'un moyen plus simple de gérer les licences avec le BlueXP digital wallet

Vous pouvez désormais bénéficier d'une gestion simplifiée des licences Cloud Volumes ONTAP en utilisant des points de navigation améliorés au sein du BlueXP digital wallet:

* Accédez facilement aux informations de votre licence Cloud Volumes ONTAP via les onglets *Administration > Licenses and subscriptions > Présentation/Licences directes*.
* Sélectionnez *View* dans le panneau Cloud Volume ONTAP de l'onglet *Overview* pour obtenir une compréhension complète de vos licences basées sur la capacité. Cette vue avancée offre un aperçu détaillé de vos licences et abonnements.
* Si vous préférez l'interface précédente, vous pouvez sélectionner le bouton *Passer à l'affichage classique* pour afficher les détails des licences par type et modifier les méthodes de facturation de vos licences.


link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-capacity-licenses.html["Gérer les licences basées sur la capacité"^].
