= Prise en charge de Google Cloud Infrastructure Manager
:allow-uri-read: 




[[support-for-google-cloud-infrastructure-manager]]
=== Prise en charge de Google Cloud Infrastructure Manager

Cloud Volumes ONTAP 9.16.1 et versions ultérieures prennent désormais en charge  https://docs.cloud.google.com/infrastructure-manager/docs/overview["Google Cloud Infrastructure Manager"^] (IM) au lieu de  https://docs.cloud.google.com/deployment-manager/docs/deprecations["Cloud Deployment Manager"^] (DM) pour les nouveaux déploiements sur Google Cloud. Google va déprécier Deployment Manager en tant que service d'infrastructure dans un avenir proche au profit d'Infrastructure Manager, plus avancé.

À compter du 9 février 2026, Cloud Volumes ONTAP utilise Infrastructure Manager pour les déploiements nouveaux et existants. Ce tableau explique quelques flux de travail pour vous :

[cols="1,4,1,1,1,1"]
|===
| Scénario | Action | Nouvelles API pour l'agent | Nouvelles autorisations pour l'agent | Nouvelles API Google Cloud pour Cloud Volumes ONTAP | Ressources documentaires 


| Agent existant et déploiement Cloud Volumes ONTAP existant | Ajoutez de nouvelles API et autorisations à l'agent existant et convertissez le système Cloud Volumes ONTAP existant.  a| 
* API Cloud Infrastructure Manager
* API Cloud Quotas

 a| 
Toutes les autorisations listées pour la version Console sur :

* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#08-december-2025["8 décembre 2025"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#09-february-2026["09 février 2026"^]

| \https://www.googleapis.com/upload/storage/v1 \https://config.googleapis.com/v1  a| 
https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-gcp-dm-im-conv.html["Configurer les déploiements Cloud Volumes ONTAP existants pour Google Cloud Infrastructure Manager"^]



| Agent existant et nouveau déploiement Cloud Volumes ONTAP | Ajoutez de nouvelles API et autorisations à l'agent existant et déployez un nouveau système Cloud Volumes ONTAP.  a| 
* API Cloud Infrastructure Manager
* API Cloud Quotas

 a| 
Toutes les autorisations listées pour la version Console sur :

* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#08-december-2025["8 décembre 2025"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#09-february-2026["09 février 2026"^]

| Toutes les étapes pour un nouveau déploiement  a| 
https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-getting-started-gcp.html["Premiers pas avec Cloud Volumes ONTAP dans Google Cloud"^]



| Nouvel agent et nouveau déploiement | Créez un nouvel agent et déployez un nouveau système Cloud Volumes ONTAP. |  |  |   a| 
* https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-google-gcloud.html["Créer un agent de Console à partir de Google Cloud"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-getting-started-gcp.html["Premiers pas avec Cloud Volumes ONTAP dans Google Cloud"^]


|===
Déployez Cloud Volumes ONTAP pour qu'il utilise automatiquement Infrastructure Manager ou basculez vos déploiements existants dans Deployment Manager vers Infrastructure Manager en exécutant un outil de conversion. La conversion est un processus unique, après quoi vos systèmes commenceront à utiliser Infrastructure Manager. Reportez-vous à  https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-gcp-dm-im-conv.html["Configurer les déploiements Cloud Volumes ONTAP existants pour Google Cloud Infrastructure Manager"^] pour obtenir des instructions sur l'exécution de l'outil de conversion.

Les systèmes Cloud Volumes ONTAP qui utilisent Infrastructure Manager utilisent des buckets Google Cloud Storage pour stocker les données et les enregistrements dans la zone du premier déploiement afin de conserver les enregistrements de déploiement, qui sont réutilisés pour les déploiements suivants. Des frais supplémentaires peuvent s’appliquer pour ces buckets, mais ne modifiez ni ne supprimez les buckets ou leur contenu :

* `gs://netapp-cvo-infrastructure-manager-<project id>` : pour les versions ONTAP et les modèles Terraform SVM utilisés pour les nouveaux déploiements Cloud Volumes ONTAP. À l'intérieur, le compartiment  `dm-to-im-convert` contient les fichiers Terraform de Cloud Volumes ONTAP.
* `<gcp project number>-<region>-blueprint-config`: pour stocker les artefacts Google Cloud Terraform.


.Liens connexes
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-getting-started-gcp.html["Premiers pas avec Cloud Volumes ONTAP dans Google Cloud"^]
* https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#console-agent-4-2-0["NetApp Console Agent 4.2.0 Notes de version"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Autorisations requises pour Google Cloud Infrastructure Manager"^]

