= Prise en charge des nouvelles instances EC2 pour Cloud Volumes ONTAP dans AWS
:allow-uri-read: 




[[support-for-new-ec2-instances-for-cloud-volumes-ontap-in-aws]]
=== Prise en charge des nouvelles instances EC2 pour Cloud Volumes ONTAP dans AWS

Cloud Volumes ONTAP 9.16.1 et versions ultérieures prennent en charge les familles d'instances EC2 M6id et M6idn pour les déploiements à nœud unique et à haute disponibilité (HA) sur AWS, qu'ils soient nouveaux ou existants. Ces instances de 6e génération offrent une puissance de traitement plus rapide, des capacités réseau renforcées et des performances supérieures aux systèmes à usage général de 5e génération.

* Instances M6id : Elles offrent un équilibre entre puissance de calcul et mémoire grâce à un stockage NVMe local haute vitesse et faible latence. Toutes les tailles d’instances M6id prennent en charge le cache Flash. Ces instances sont parfaitement adaptées aux charges de travail telles que l’enregistrement de données et le traitement multimédia.
* *Instances M6idn* : Offrent les mêmes capacités de stockage NVMe local que les instances M6id. Toutes les tailles d’instances M6idn prennent en charge Flash Cache.


Nous déconseillons les instances de petite taille m6id.xlarge, m6id.2xlarge, m6idn.xlarge et m6idn.2xlarge pour les charges de travail exigeantes en termes de performances ou de mémoire. Pour ces charges de travail, privilégiez une instance dotée d'un nombre de cœurs plus élevé et d'une mémoire plus importante.

Pour plus d'informations, consultez  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Configurations prises en charge pour Cloud Volumes ONTAP dans AWS"^].
